title: 
author: 
email: 
logo: 
colophon: 
description_tagline: 
description: >- # this means to ignore newlines until "baseurl:"
  Lorem ipsum dolor sit amet
  consectatur
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  
rss: RSS

# Build settings
theme: aemi
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  -
    scope:
      path:   "assets/**/*"
    values:
      sitemap: false
  -
    scope:
      path:   "assets/*"
    values:
      sitemap: false
