title: Aemi Theme Website
author: "Guillaume"
email: public@gcqd.fr
logo: 
colophon: 
description_tagline: 
description: >- # this means to ignore newlines until "baseurl:"
  Lorem ipsum dolor sit amet
  consectatur
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com 

# Build settings
theme: aemi
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - fonts.txt
  - /*.gem
  - /*.gemspec
  - README.md
  - LICENSE.txt
  - scripts/*

defaults:
  -
    scope:
      path:   "assets/**/*"
    values:
      sitemap: false
  -
    scope:
      path:   "assets/*"
    values:
      sitemap: false
